### ISSUE TITLE
提问请教：一个task被node apply之后，到状态机从日志读取出来，中间的过程是什么样子的？

### ISSUE THREAD

**Issue by MyXOF** [alipay/sofa-jraft#100]
一个task从`service.getNode().apply(task);`到状态机里面iterator取出来，中间会有一个时间差，如果这个task本身执行花的时间很小，但是这个时间差相对很大。那么是不是上面这个过程就会成为性能的瓶颈？

我的场景是，只有一个客户端往一个单节点的raft组里面提交任务，发现用raft的方式和不用raft本地执行，性能差了3倍。假设一个任务真正执行要花20ms，上面的那个过程却要花40ms。

一开始我以为状态机取日志的时候，会攒够一批再执行，也就是看到了applyBatch这个参数，默认是32，但是我一个客户端每次都只发一个任务，等这个任务做完之后才会发下一个，按照这个参数似乎应该卡住才对。我又把它调整成1，发现最开始说的那个过程仍然要花40ms，感觉这个参数是不是我理解的不对？

是不是从apply(task)到iterator取出来中间有一个固定的时间开销，即使把applyBatch这个参数调成1也一样会有？

**Comment by pifuant** [comment]
applyBatch只是针对leader写log的优化

**Comment by fengjiachun** [comment]
>一开始我以为状态机取日志的时候，会攒够一批再执行
jraft 中不存在延时攒批的行为，executeApplyingTasks 的条件是 applyBatch || endOfBatch
其中 endOfBatch 是 disruptor 的参数，代表当前 event 是否是 RingBuffer 中的的最后一个 event，所才不会出现你说的那种卡住的情况，是没有延时的

>是不是从apply(task)到iterator取出来中间有一个固定的时间开销
没有固定的时间开销，但是走一遍 raft 流程，相比不走 raft log，多余开销是一定有的，比如写 raft 日志的开销等，通常情况下，如果只针对单个请求来看，一定的延时开销是有的，但 jraft 基本不会显著降低你的系统的吞吐，需要整体来看，从我们自己的测试数据看，三副本的 jraft 整体吞吐和 rpc 的吞吐上限是差不太多的

冒昧问下，你说的多花了 40ms 的情况，是单副本？ 是怎么测得？ jmh benchmark ？ 有预热吗？ 还是只是简单写代码比较了下单个请求？

最后，对于 service.getNode().apply(task) 这个 api，它是可以保证你的 apply 顺序的，你的场景是一定要一个一个的串行执行吗？

**Comment by MyXOF** [comment]
是单副本的情况，我是在这两个地方分别打了一条日志，然后相减得到的时间，没做什么预热。
```java
    LOGGER.info("apply at {}", System.currentTimeMillis());
    service.getNode().apply(task);
-------------------------------------
  public void onApply(Iterator iterator) {
    while (iterator.hasNext()) {
      LOGGER.info("iterator start at {}", System.currentTimeMillis());
```
我在做分布式数据库写入的性能测试，我每次会发一批SQL语句过来，然后记到raft日志里面，然后状态机里面读出来执行，我发现我这批SQL语句执行大概花了20ms，但是上面的那个过程花了40ms


`最后，对于 service.getNode().apply(task) 这个 api，它是可以保证你的 apply 顺序的，你的场景是一定要一个一个的串行执行吗？`这句话我没太理解，因为是数据插入操作，得保证先后执行的顺序，不能并发

**Comment by MyXOF** [comment]
感觉如果请求的操作如果本地状态机能够以很短的时间执行，那么从apply(task)到iterator取出来的时间开销就会成为瓶颈，但是如果请求的操作要花相对长的时间去执行，那么这块时间所占的比重相对较小，可以忽略不计

**Comment by fengjiachun** [comment]
>最后，对于 service.getNode().apply(task) 这个 api，它是可以保证你的 apply 顺序的，你的场景是一定要一个一个的串行执行吗？这句话我没太理解，因为是数据插入操作，得保证先后执行的顺序，不能并发

我的意思是，apply(task) 是什么顺序，onApply(iteratior)被调用时  iterator 是一样的顺序，你可以一次 apply 多条数据的

**Comment by fengjiachun** [comment]
> 我在做分布式数据库和单机版数据库写入的性能测试，我每次会发一批SQL语句过来，然后记到raft日志里面，然后状态机里面读出来执行，我发现我这批SQL语句执行大概花了20ms，但是上面的那个过程花了40ms

建议写个 benchmark 吧，最好预热， jraft 有详细的 metric 指标统计，基本可以看到哪里处理慢

**Comment by fengjiachun** [comment]
打开 metric 可以参考一下代码

https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java#L415

**Comment by MyXOF** [comment]
好的，多谢了
