### ISSUE TITLE
关于节点启动流程的疑问

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#102]
请教一下，我理解的raft的启动流程是这样的，把StateMachine清理掉，通过snapshot和raft log恢复StateMachine。
请问jraft是这样处理的吗？
小弟眼拙，通过snapshot恢复StateMachine找到了，但是如果还没有snapshot时，清理sm并通过raft log恢复sm这部分并没看太清楚，求指教。

**Comment by fengjiachun** [comment]
NodeImpl#init() -> initSnapshotStorage() -> this.snapshotExecutor.init(opts) ->this.fsmCaller.onSnapshotLoad(done)
接下来就会调用到用户自己实现的 StateMachine.onSnapshotLoad()

StateMachine 清理是用户状态机需要实现的

**Comment by shiftyman** [comment]
如果此时snapshot还没创建呢？但是已经有raft log

**Comment by fengjiachun** [comment]
>如果此时snapshot还没创建呢？但是已经有raft log
如果没有Snapshot 就相当于 last index 为 0，回放过程其实就是走的通用的 apply 流程了

**Comment by shiftyman** [comment]
但是sm没有清理啊？直接apply非幂等操作会不会有问题？

**Comment by fengjiachun** [comment]
sm 是用户的，需要自己清理，不清理是有问题的

**Comment by shiftyman** [comment]
get ， 那就是节点启动前清理比较合适，不然apply的时候并不知道是不是需要清理

**Comment by fengjiachun** [comment]
唠到这儿，感觉是不是应该强制 StateMachine 必须实现一个 clear() 接口在启动前由 jraft 调用以保证清除数据

**Comment by shiftyman** [comment]
我认为有必要，因为不是所有使用者都那么熟悉Raft，而且也不应该要求他们做到这一点

**Comment by killme2008** [comment]
@fengjiachun 我觉的不需要，因为状态机都是用户构造传入的，他有完全充分的掌控权，可以在传入之前做清理。没有特别的必要，还是不增加新的方法。

@shiftyman  这是一个 raft 算法库，想使用好，都应当去熟悉 raft 算法的，否则就是盲人摸象了。

**Comment by killme2008** [comment]
这里可以做的事情，可以在开发指南里强调这一点。

**Comment by fengjiachun** [comment]
emmm 我觉得即使对 raft 有一定程度了解的人也容易犯这个错误，最主要就是有快照没快照是不同的行为，有快照相当于 clear 了，没快照就要用户启动 sm 时自己处理，如果没有启动时清理，问题不容易被立刻暴露，只有非幂等操作才会出问题

**Comment by killme2008** [comment]
@fengjiachun 这里有没有这个 clear 方法，用户都需要理解这个行为的。你想下，假设有了 clear 方法，用户同样需要理解 clear 是干什么的，什么时候会被调用，我应该怎么实现这个方法，并没有区别。这是本质复杂度。

**Comment by pifuant** [comment]
如果有snapshot， 则基于snapshot， 如果没有则基于zero
然后apply log

默认回滚到last snapshot point呢

**Comment by fengjiachun** [comment]
> 如果有snapshot， 则基于snapshot， 如果没有则基于zero
> 然后apply log
> 
> 默认回滚到last snapshot point呢

主要是 jraft 没有强制 sm 必须实现 onSnapshotLoad 方法，用户如果没有配置 Snapshot uri 是不会调用 onSnapshotLoad 方法的

**Comment by killme2008** [comment]
@fengjiachun 这个在文档里强调下，放到 snapshot 和启动两个小节里。我先关闭了。
