### ISSUE TITLE
Supports LogEntry checksum validation

### ISSUE THREAD

**Issue by killme2008** [alipay/sofa-jraft#105]
### Your question

LogEntry doesn't have any data validation mechanisms to make sure that the log data is not corrupted after transfering from disk or network.

### Your scenes

It's a data risk when log entry is corrupted. We should have a mechanism to prevent this problem.

### Your advice

Adds a data checksum validation for log entry, user can choose whether to enable this feature.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by marsbible** [comment]
absolutely necessary feture in production
