### ISSUE TITLE
ReadOnlyServiceImpl里的Disruptor使用问题

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#120]
ReadIndexResponseClosure里持有RingBuffer里的ReadIndexEvent对象，发起node.handleReadIndexRequest请求异步回调Closure，这里切换了线程，ReadIndexEvent里面的值是有可能被addRequest操作覆盖的

**Comment by fengjiachun** [comment]
@gumandy 非常感谢指出这个问题，确实是 bug

**Comment by fengjiachun** [comment]
这个问题确实是个 bug，但是不影响 readIndex 读的正确性和一致性
对稳定性会有一定影响，就是前面的read 被 notifyFail 却影响了新进来的 read 请求返回失败，需要重试解决
在 rheakv 中，readIndex 失败会走 raft log 读，可以借鉴

**Comment by gumandy** [comment]
@fengjiachun  前面read由于closure被覆盖都得不到notify了，直到超时，这。。。。。。。。。。。

**Comment by fengjiachun** [comment]
恩，被覆盖的需要等到超时
