### ISSUE TITLE
jraft是否支持其他rpc框架

### ISSUE THREAD

**Issue by wy223170** [alipay/sofa-jraft#125]
hi，我看CounterServer的demo，jraft现在的rpc框架使用的是sofarpc，请问下jraft能否支持其他rpc框架？

**Comment by fengjiachun** [comment]
你好，jraft 是基于 [bolt](https://github.com/alipay/sofa-bolt) 通信，sofa-rpc 也是同样基于 bolt
在 jraft 层面，通信只支持 bolt。
在应用层面是没有限制的，你可以使用 jraft 的同时再使用其他 rpc 框架，没有冲突

**Comment by wy223170** [comment]
谢谢回复。截图里的两个方法是客户端获取配置和leader的。这两个方法应该都是依赖了bolt通信。我的问题是能不能业务的client不用去感知到bolt rpc，只需要业务server使用jraft时自带bolt即可？
![1](https://user-images.githubusercontent.com/16471346/56552341-8ec4d780-65bd-11e9-9386-5b47e6898fd2.png)

**Comment by fengjiachun** [comment]
业务 server 共享 jraft 中的 bolt？ 可以

**Comment by wy223170** [comment]
了解了，感谢回答
