### ISSUE TITLE
Get sequence again in RheaKV by bGetSequence

### ISSUE THREAD

**Issue by masaimu** [alipay/sofa-jraft#128]
### Your question

How can i get the same sequence again when i use com.alipay.sofa.jraft.rhea.client.RheaKVStore#bGetSequence(java.lang.String, int) to get sequence.

### Your scenes

Each bGetSequence method call will lead to sequence increase by step, so other client or thread cannot get the current sequence. In my scenes, i have to store this sequence in addition.

### Your advice

If bGetSequence method allows step parameter to be zero, this question will be solved simply.

### Environment

- SOFAJRaft version: 1.2.3

**Comment by fengjiachun** [comment]
This feature will be supported in v1.2.6 at the latest.
