### ISSUE TITLE
Change the jdk version in travis

### ISSUE THREAD

**Issue by slievrly** [alipay/sofa-jraft#13]
We should use openjdk instead of oraclejdk because oraclejdk will charge. Openjdk8 and openjdk11 will be used as two versions of the official long-term maintenance. At the same time, openjdk11 has a lot of syntax adjustments, so it needs to do the corresponding compatibility test.

**Comment by fengjiachun** [comment]
@slievrly tks

**Comment by slievrly** [comment]
@fengjiachun ^_^
