### ISSUE TITLE
RheaKV状态机apply时多节点不一致漏洞

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#136]
RheaKV的rocksDB状态机，比如put，当rocksdb的put成功，则给client返回success，异常，则给client返回错误。

我认为这里有漏洞。
首先，状态机Apply时，log已经同步大多数节点，那么leader apply失败，不代表follower也apply失败吧？

非必然失败，这种应该抛出异常，等待下次apply重试才是。
必然失败（能确定leader和follower必定apply失败），这种可以响应client失败。

**Comment by killme2008** [comment]
@fengjiachun 这里似乎确实有问题，遇到异常应该调用 `Iterator#setErrorAndRollback` 来终止状态机。

**Comment by shiftyman** [comment]
Iterator#setErrorAndRollback  是什么用途，请指教。
我理解这里直接抛出异常，applyindex也不会前进，下次就会重试即可

**Comment by fengjiachun** [comment]
这里分两种情况：
1. 程序正常逻辑中的执行失败，这种情况不论 leader 还是 follower 他们的入参（输入数据即 log）均是一模一样的，程序的执行逻辑中的变量部分全部来自入参，所以执行结果都一样，要失败都失败
2. 某个节点代码逻辑以外的故障，比如磁盘满了无法写入，硬件故障等，那么重试也是大概率失败，并且即使 leader 失败， follower 成功也保证不了状态机形成多数派，所以给 client 返回失败

**Comment by fengjiachun** [comment]
> @fengjiachun 这里似乎确实有问题，遇到异常应该调用 `Iterator#setErrorAndRollback` 来终止状态机。

如果应用处理我上面说的第二种异常，只能终止状态机

**Comment by killme2008** [comment]
@shiftyman  遇到不可恢复的异常，比如 IO 磁盘占满之类，可以调用`setErrorAndRollback` 回滚 iterator ，其实也就将 appliedIndex 回退，等修复后重新应用。

**Comment by fengjiachun** [comment]
@killme2008 重试是不行的，只能终止状态机从头恢复日志，重试会把非幂等操作的数据搞坏

**Comment by killme2008** [comment]
@fengjiachun   `setErrorAndRollback` 会终止状态机的，我说的是修复后重新应用。

**Comment by shiftyman** [comment]
看你rocksdb的操作，不可能是第一种情况，leader和follower都失败。
这里抛异常的话，applyindex也不会前进的，下次会重试。
重试没问题吧？上次失败了，这次重试也就做了一次

**Comment by shiftyman** [comment]
会不会有可能偶发异常，重试就能解决，非要终止状态机？

**Comment by killme2008** [comment]
@shiftyman 这是需要状态机的实现者来区分并保证的，不可恢复的异常才应该setError终止。

**Comment by fengjiachun** [comment]
> 会不会有可能偶发异常，重试就能解决，非要终止状态机？

我上面列出了两种情况，第一种情况重试是完全错误的逻辑，第二种情况，重试也不会成功

**Comment by shiftyman** [comment]
是的，我说的情况针对RheaKV，不是jraft

**Comment by shiftyman** [comment]
第一种情况，Rheakv不会出现；第二种，重试不会成功，不好说，比如，一刹那磁盘满，但是下一刻某进程清理了空间呢？^^(天马行空一下)

**Comment by shiftyman** [comment]
或者挂载的网络磁盘，偶尔网络抖动也有可能呀

**Comment by killme2008** [comment]
从保证数据正确性的角度，IO 异常还是终止状态机更为安全。java 的 IO 异常基本都是确实存在软硬件故障或者权限等问题的的时候才会发生。

**Comment by fengjiachun** [comment]
> 或者挂载的网络磁盘，偶尔网络抖动也有可能呀

这种情况也不能重试的，rheakv 状态机有非幂等操作，重试就无法保证所有节点状态机一致了，所以要处理也是终止状态机，想要恢复需要清空状态机从头恢复

**Comment by killme2008** [comment]
@fengjiachun  我感觉文档里可能缺少了这部分描述 ，我来补充下，原来没有特别强调。

**Comment by shiftyman** [comment]
简单看了下setErrorAndRollback ，没发现哪里有终止状态机的逻辑。
请教下setErrorAndRollback 如何终止状态机，node会shutdown吗？最好有接口通知上层业务这个事件发生了

**Comment by killme2008** [comment]
@shiftyman  是在 `FSMCallerImpl` 的 `doCommitted` 方法：

```java

            if (iterImpl.hasError()) {
                setError(iterImpl.getError());
                iterImpl.runTheRestClosureWithError();
            }
```

**Comment by shiftyman** [comment]
是否终止状态机取决于用户如何实现fsm.onError;
并且，node也没有shutdone，知识stepdown。

貌似这种处理还不是太理想吧？

**Comment by killme2008** [comment]
@shiftyman 不仅仅是 stepdown的，请注意 `Node#onError` 会设置 state 为 `STATE_ERROR`，后续所有的 task 提交都将直接失败，这个节点也就 halt 了。

**Comment by killme2008** [comment]
同时 FSMCallerImpl 也设置了 error，后续的 snapshot、apply 等等请求也都会被阻止的。

**Comment by fengjiachun** [comment]
把异常归为 2 类：
1. 入参部分（raft log）检查失败异常
2. 其他一切异常

对于 1， 正常返回 client 失败， 对于 2 ，终止状态机保证后续任何 apply 和 snapshot 都不能进行，如要恢复需要从正确的 snapshot + raft log 回放 （实际上就是重启）
