### ISSUE TITLE
非一致性读的情况下，follower在Candidate状态可以正常处理读请求吗？

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-jraft#148]
![image](https://user-images.githubusercontent.com/1046037/57190710-37751e80-6f50-11e9-9b19-deacf90d4b64.png)
看代码感觉是可以正常处理的。
如果是这样的话，感觉有问题啊，网络隔离的情况下，一个节点永远选举不成功，永远都是Candidate状态，读到的就永远是过期的数据了。

**Comment by fengjiachun** [comment]
非一致性读(readOnlySafe==false)的情况下，是完全脱离一切 raft 算法相关保障的，对于过期（或者说一致性）的问题根本不做任何保证，这种场景只是利用 raft 做一下多节点的数据同步，有一些 cache 场景会用到

**Comment by fengjiachun** [comment]
没其他问题先 close
