### ISSUE TITLE
ReadLease 的处理似乎并不严谨

### ISSUE THREAD

**Issue by PFZheng** [alipay/sofa-jraft#25]
简单的阅读了一下 read lease 部分处理的代码，发现read lease只是判断了状态是不是STATE_LEADER。

考虑这样一个case。一个 {A,B,C} raft 复制组，刚开始一切正常。过了一段时间 A和C发生了网络分区，这样{A,B}因为能达到多数，所以仍然能正常工作。在网络分区后，没有任何新日志被写入，所以几个副本的数据是完全一致的。C在election timeout后发起选主，然后和B达成一致，C成为新leader。这时候，A的心跳还没到达B，所以A这是stale leader。在A发现有新主之前，新日志被写下了。这时，A的状态其实仍然是STATE_LEADER。按照代码的实现，仍然在提供读，发生了stale read。

**新leader在起来之后，应该等待一段时间才能处理请求，确保老leader的lease过期。这个时长应该超过lease period。**

目前，在代码中没有看到相关的处理。当然，可能是我看得不够仔细。

**Comment by pifuant** [comment]
可以参考paxos made live给出的方案， 让follewer在lease周期内不接受选举产生新的leader就可以了

**Comment by pifuant** [comment]
In our implementation, all replicas implicitly grant a lease to the master of the previous Paxos instance
and refuse to process Paxos messages from any other replica while the lease is held. The master maintains
a shorter timeout for the lease than the replicas – this protects the system against clock drift. The master
periodically submits a dummy “heartbeat” value to Paxos to refresh its lease.

**Comment by PFZheng** [comment]
@pifuant 我的疑问是sofa-jraft目前的实现似乎没有保证这个

**Comment by pifuant** [comment]
@PFZheng 我也似乎没看到相关处理

**Comment by killme2008** [comment]
@PFZheng  @pifuant 其实有处理的，只是不是采用时间判断的方式，而是使用定时器来避开，请参考 `handleElectionTimeout` 实现，这是定时器定期调用，间隔就是 election timeout。preVote 的发起只能在 lastLeaderTimestamp 过期的情况下才会发起。follower 保证在没有收到更新的 leader 请求后才会发起 preVote。

**Comment by killme2008** [comment]
仔细思考了下，这里存在的问题跟 #15 类似，issue 中描述的场景确实可能出现，出现了两个分割的 majority： (A, B）　和  (B, C)，又凑巧出现写入极少或者没有的情况， A无法及时发现 C成为了新的 leader，在 1个 hearbteat 周期内，C又刚好写入了新日志，这样 A 会认为自己是 leader，而出现了 stale read，应当在 preVote 加入租约有效期的判断，来避免 C 成为新的 leader。

感谢分析。

**Comment by PFZheng** [comment]
> 仔细思考了下，这里存在的问题跟 #15 类似，issue 中描述的场景确实可能出现，出现了两个分割的 majority： (A, B）　和 (B, C)，又凑巧出现写入极少或者没有的情况， A无法及时发现 C成为了新的 leader，在 1个 hearbteat 周期内，C又刚好写入了新日志，这样 A 会认为自己是 leader，而出现了 stale read，应当在 preVote 加入租约有效期的判断，来避免 C 成为新的 leader。
> 
> 感谢分析。

看了这个，的确可以用同一方法来解决😊。我建议可以另外提供一个lease timeout的参数。

**Comment by PFZheng** [comment]
赞一个，你们的回复速度很快

**Comment by pifuant** [comment]
```
            this.checkReplicator(peer);
            if (nowMs - replicatorGroup.getLastRpcSendTimestamp(peer) <= options.getElectionTimeoutMs()) {
                aliveCount++;
                continue;
            }
            deadNodes.addPeer(peer);
 
```

这里的replicatorGroup.getLastRpcSendTimestamp(peer)是不是应该判断下是已经收到peer response确认过的，而不单单只是SendTimestamp。

**Comment by killme2008** [comment]
@pifuant 他是 Replicator 里的 lastRpcSendTimestamp，每次在 rpc response 返回后更新的。名字可能误导你了。

**Comment by pifuant** [comment]
@killme2008 thx, 由于时钟偏移， 判断lease有效时， 是不是用小于options.getElectionTimeoutMs()的某个值代替options.getElectionTimeoutMs()更好一点呢

**Comment by killme2008** [comment]
@pifuant  因为 heartbeat  的周期是 electionTimeout 的十分之一，这个`小于getElectionTimeoutMs多少的值`如何设置都不会完全合理，保持目前这个判断可以接受了。

**Comment by fengjiachun** [comment]
这个 bug 已在 v1.2.4中发布解决，先关闭了
