### ISSUE TITLE
求问有release版本可以用吗？

### ISSUE THREAD

**Issue by wakwaniu** [alipay/sofa-jraft#35]
求问有release版本可以用吗？

**Comment by killme2008** [comment]
你好，现在 maven 1.2.3 的版本就是稳定版本。目前发现的问题是在线性一致读使用 ReadLease 的时候，分区并且极少写入的情况下可能遇到双主问题引起的脏读，线性一致读我们推荐使用 `ReadOnlyOption.ReadOnlySafe` 选项，也是默认选项。

**Comment by killme2008** [comment]
没有更多问题我先关闭了。
