### ISSUE TITLE
RheaKV多Region共享StateMachine的疑问

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#37]
刚刚阅读了下RheaKV的代码，收获颇丰，但是有个疑问，甚是不解，希望指导一下。

RheaKV采用multi-raft的设计，但一个节点的多个region共享一个RocksDB状态机。
这样，snapshot是以整个节点所有region的维度来做的。
那么，当一个raft group的leader和follower之间做install snapshot时，是否会把leader所在的节点的所有数据（包括所有的raft group）都install过去了？

此处看了好久，也没有看到怎么把不同raft group的数据区分开，还望赐教。

**Comment by fengjiachun** [comment]
@shiftyman 看的真仔细，是的，目前 snapshot 是全部 region 的维度来做的，这个是待优化的点
不过严格来讲，也不是多个 region 共享一个状态机，每个 region 都有独立` KVStoreStateMachine`，不过存储（RocksRawKVStore/MemoryRawKVStore）是所有 region 共享的

**Comment by shiftyman** [comment]
嗯嗯，弱弱问一句，这里除了不共享raw kv store, 还有更好的优化思路吗？^^

**Comment by fengjiachun** [comment]
可能后面要修改 onSnapshotSave() ，当一个 region 做 snapshot 时只生成它 key range 的 sst file, 
install snapshot 时也选择 ingest sst file 的方式

https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files

如果你有更好的方案也欢迎提出来

**Comment by fengjiachun** [comment]
@shiftyman 见  https://github.com/alipay/sofa-jraft/pull/42

**Comment by shiftyman** [comment]
很好
