### ISSUE TITLE
提问请教:为什么jraft选主每个node只需发送一轮voteRequest,而ZAB协议需要发送多轮?

### ISSUE THREAD

**Issue by reenWYJ** [alipay/sofa-jraft#40]
ZAB协议中,peer更新currentNode后,需要重新发送notification
为什么jraft更新currTerm和lastLogId不需要再继续发送Request

这样设计和zab孰优孰劣呢?

**Comment by reenWYJ** [comment]
会看了zk的代码,发现zk通过多轮notification的发送在最后让每个节点都存下了大于quorum一半数量的最终的vote,并且在选举最后确定了每个节点的角色

而jraft在选举中只会确定确定leader,Follower并不确定leaderId,在之后的logAppend中才会设置leaderId

**Comment by killme2008** [comment]
raft 或者 zab 都是 paxos 的变形。两者的算法其实是非常类似的，算法过程上少许的变形和优化。

raft 在选举产生 leader 后，通过一次 configuration change commit 将 leader 确认广播(AppendEntries协议) 给所有 follower，可以类比于 zab 论文中的 `NEWLEADER` 和 `ACK-LD` 阶段。

**Comment by killme2008** [comment]
补充：  新 leader 将 configuration change commit 将 leader 确认广播(AppendEntries协议) 给所有 follower，这个代码在 `NodeImpl#becomeLeader()` 中的

```java
this.confCtx.flush(this.conf.getConf(), this.conf.getOldConf());
```

调用。

**Comment by killme2008** [comment]
因为这个 issue 不涉及 jraft 本身，我先关闭了，两者差异的解读，我建议阅读这篇论文

http://101.96.10.64/www.cs.cornell.edu/fbs/publications/viveLaDifference.pdf
