### ISSUE TITLE
性能测试工具？

### ISSUE THREAD

**Issue by bruceshao** [alipay/sofa-jraft#44]
是否有性能测试的工具？有比较多的raft备选方案，现在需要选择一个，期望给出性能测试的工具或者结果

**Comment by fengjiachun** [comment]
你好，这里是目前的 Benchmark 数据 https://github.com/alipay/sofa-jraft/wiki/Benchmark-%E6%95%B0%E6%8D%AE
Benchmark 代码在这里 https://github.com/alipay/sofa-jraft/tree/develop/jraft-example/src/main/java/com/alipay/sofa/jraft/benchmark

**Comment by bruceshao** [comment]
@fengjiachun 感谢~

**Comment by JerryYangSH** [comment]
@fengjiachun 请问有文档介绍 如何跑性能测试吗？ 具体命令 参数？
