### ISSUE TITLE
FSMCallerTest的testOnCommittedError前三行代码是无用的，可以去掉

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-jraft#45]
@Test
    public void testOnCommittedError() throws Exception {
        final LogEntry log = new LogEntry(EntryType.ENTRY_TYPE_DATA);
        log.getId().setIndex(11);
        log.getId().setTerm(1);
        Mockito.when(logManager.getTerm(10)).thenReturn(1L);
前3行是无用的，在setup中就有了 
       opts.setBootstrapId(new LogId(10, 1));

**Comment by fengjiachun** [comment]
@huangyunbin 感谢，ci 通过后会合并
