### ISSUE TITLE
wiki的错别字

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-jraft#48]
https://github.com/alipay/sofa-jraft/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E4%B8%80%E8%87%B4%E6%80%A7%3A-Raft-%E4%B8%8E-JRaft

![image](https://user-images.githubusercontent.com/1046037/54520169-0db56780-49a3-11e9-9022-94bbad5210ee.png)

良心-》良性？ 还是直接去掉

**Comment by fengjiachun** [comment]
你好 改掉了 哈哈

**Comment by fengjiachun** [comment]
已经修改了哈，我先close了
