### ISSUE TITLE
提问请教：example子项目里面关于CounterServer的redirect()方法作用

### ISSUE THREAD

**Issue by MyXOF** [alipay/sofa-jraft#52]
你好，在读example子项目源码的时候看到CounterServer类中的redirect函数有点不太理解

```java
public ValueResponse redirect() {
    final ValueResponse response = new ValueResponse();
    response.setSuccess(false);
    if (this.node != null) {
        final PeerId leader = this.node.getLeaderId();
        if (leader != null) {
            response.setRedirect(leader.toString());
        }
    }
    return response;
}
```

这里设置了`response.setRedirect(leader.toString());`但是没有看到ValueResponse中getRedirect()方法被调用过。

在IncrementAndGetRequestProcessor类中，

```java
@Override
public void handleRequest(final BizContext bizCtx, final AsyncContext asyncCtx, final IncrementAndGetRequest request) {
    if (!this.counterServer.getFsm().isLeader()) {
        // 这里要重定向到leader，但是却没有看到用ValueResponse中getRedirect()方法同获取leader，不知道是怎么做到重定向的
        asyncCtx.sendResponse(this.counterServer.redirect());
        return;
    }
    ...
}
```

感觉ValueResponse中的redirect没什么用。不知道我理解的对不对。

**Comment by fengjiachun** [comment]
你好，Counter 例子只是提供一种 leader 切换时的处理思路，redirect 没有在 client 实现，只是打出了日志（日志包含 redirect 值）

**Comment by MyXOF** [comment]
那我理解的`asyncCtx.sendResponse()`方法是把返回的response值重定向到leader节点，但是如何找到leader由内部逻辑实现，不需要开发者手动指定

**Comment by fengjiachun** [comment]
jraft-core 层面不会负责 redirect ，需要用户自行实现，我感觉你可以看下 rheakv 模块，这个模块包含了完整的类似 redirect 实现

**Comment by MyXOF** [comment]
也就是一个raft group的某个节点接到客户端的请求，如果它不是这个group的leader，那它需要将客户端的请求转发到leader。这个过程需要用户自己实现？

**Comment by killme2008** [comment]
@MyXOF 是的，目前我们实现这个脚手架，我们推荐遇到这种leader变换走推拉结合的方式：

1. 定时通过 `RouteTable` 获取最新的 leader 信息缓存到本地客户端路由。
2. 服务端发现不是 leader，返回 redirect 请求，客户端遇到这个错误可以主动刷新，或者使用应答中的 leader 自动重试。

我们不内置这个逻辑是因为：
1. 业务的需求可能是不同的，有的业务可能是不希望重试的。
2. 本身这个逻辑不复杂，基于 RouteTable 和 bolt RPC 框架，也是比较容易实现的。

**Comment by MyXOF** [comment]
好的，我明白了，感谢答疑
