### ISSUE TITLE
ProtoBufFile#save(Message msg, boolean sync) 返回false问题

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#54]
如果ProtoBufFile.path文件已经存在，savesave将一直返回false，
LocalSnapshotCopier.internalCopy()中调用了filter();和copyFile(file);
这可能会导致调用两次LocalSnapshotWriter.sync()，第一次返回ture，第二次返回false

**Comment by killme2008** [comment]
你是 windows 环境？

**Comment by gumandy** [comment]
@killme2008 是的

**Comment by killme2008** [comment]
sorry， jraft 没有在 windows 下测试过，目前来看 windows 也不支持原子的 move 操作，我们会想办法解决下。
