### ISSUE TITLE
1.2.4 发布

### ISSUE THREAD

**Issue by killme2008** [alipay/sofa-jraft#56]
* [x] 单元测试通过
* [x] jepsen 验证通过
* [x] 文档补充
* [x] 发布和 release note

**Comment by fengjiachun** [comment]
---
## 1.2.4
2019-03-20
* Bug Fixex
    - 修复一种情况下 lease read 的 stale read https://github.com/alipay/sofa-jraft/pull/34
    - 部分 timestamp 修改为 monotonic time https://github.com/alipay/sofa-jraft/issues/24
    - 修复一种情况下 replicator 被 block 住的问题 https://github.com/alipay/sofa-jraft/pull/19
    - 解决 windows 平台下某些单测无法创建目录 https://github.com/alipay/sofa-jraft/pull/51
    - 解决 windows 平台下某些 rocksdb options 设置不当导致进程 crash https://github.com/alipay/sofa-jraft/pull/22

* Features
    - 开放 RocksDB options 的设置给用户层 https://github.com/alipay/sofa-jraft/issues/20
    - Pre-vote 优化，启用 lease 机制来规避网络分区+集群长时间无写入的情况下，游离节点回归后打断当前 term，提升系统可用性 https://github.com/alipay/sofa-jraft/issues/15
    - travis ci jdk 由 oracle jdk 修改为 openjdk 并增加 openjdk 11 https://github.com/alipay/sofa-jraft/issues/13
    - 升级 bolt 到 1.5.3 https://github.com/alipay/sofa-jraft/issues/10
    - BallotBox 中的 ReadWriteLock 优化为 StampedLock 并对 lastCommittedIndex 提供乐观读实现 https://github.com/alipay/sofa-jraft/pull/3
    - 修正几个单词拼写错误
* Breaking Changes
	- 无
