### ISSUE TITLE
jraft的成熟度和使用情况如何？

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-jraft#59]
看了下jraft的源码，感觉还不错，很多细节都有考虑，对raft的实现也是比较完善。
打算使用jraft，但是如何说服其他人，说服上级呢？
如果有些成功的案例，如果是生产上已经大规模的使用，这些都会比较有说服力。

**Comment by ujjboy** [comment]
@huangyunbin  参见 https://github.com/alipay/sofa-jraft/wiki/%E7%94%A8%E6%88%B7%E6%A1%88%E4%BE%8B   这是蚂蚁内部核心中间件使用的基础框架。

**Comment by killme2008** [comment]
谢谢，你提的问题很好，也给了我们一个说明的机会。

首先，成熟度这个问题，也是我们一开始想基于 braft 做 port 的原因，我在了解和学习 braft 后，对于这个项目有了充分的理解，并且 braft 在百度也得到了大量的实际场景验证，这比我们从头开始写一个 raft 算法库是一个更好、更坚实的基础。 raft 算法虽然易于理解，但是在工程实践中还是有很多的细节需要考量，这些 corner case 的处理是最容易出问题的地方。

其次， jraft 本身的代码质量也是牢靠的，我们有非常充分的单元测试，有基于 [jepsen](https://github.com/jepsen-io/jepsen) 分布式一致性验证测试，验证了下列场景

```
随机分区，一大一小两个网络分区
随机增加和移除节点
随机停止和启动节点
随机 kill -9 和启动节点
随机划分为两组，互通一个中间节点，模拟分区情况
随机划分为不同的 majority 分组
```

在这些情况了验证了读写的一致性，包括线性一致读的实现。

最后，就是上面朋友所说， jraft 已经在蚂蚁内部一些场景落地跑了接近一年的时间，整体的稳定性受到了部分验证， 即将开源的 sofa 注册中心的选举也是基于 jraft 实现，该项目也已经在内外很多场景提供了线上服务。

感谢您的关注。

**Comment by killme2008** [comment]
jraft 开源本身也是为了接受社区的检阅和使用，帮助项目的更好的发现 bug、增加 feature，希望后续随着更多内外用户的使用，jraft 的成熟度能得到进一步的完善。

**Comment by kikimo** [comment]
> 谢谢，你提的问题很好，也给了我们一个说明的机会。
> 
> 首先，成熟度这个问题，也是我们一开始想基于 braft 做 port 的原因，我在了解和学习 braft 后，对于这个项目有了充分的理解，并且 braft 在百度也得到了大量的实际场景验证，这比我们从头开始写一个 raft 算法库是一个更好、更坚实的基础。 raft 算法虽然易于理解，但是在工程实践中还是有很多的细节需要考量，这些 corner case 的处理是最容易出问题的地方。
> 
> 其次， jraft 本身的代码质量也是牢靠的，我们有非常充分的单元测试，有基于 [jepsen](https://github.com/jepsen-io/jepsen) 分布式一致性验证测试，验证了下列场景
> 
> ```
> 随机分区，一大一小两个网络分区
> 随机增加和移除节点
> 随机停止和启动节点
> 随机 kill -9 和启动节点
> 随机划分为两组，互通一个中间节点，模拟分区情况
> 随机划分为不同的 majority 分组
> ```
> 
> 在这些情况了验证了读写的一致性，包括线性一致读的实现。
> 
> 最后，就是上面朋友所说， jraft 已经在蚂蚁内部一些场景落地跑了接近一年的时间，整体的稳定性受到了部分验证， 即将开源的 sofa 注册中心的选举也是基于 jraft 实现，该项目也已经在内外很多场景提供了线上服务。
> 
> 感谢您的关注。

可否了解下，这些 jepsen 测试你们持续运行了多长时间，运行期间系统的写入、读取负载情况如何？
