### ISSUE TITLE
jraft是运行在物理机上的吗？因为容器没有固定ip

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-jraft#60]
现在都是云化了，都是容器，容器上如何部署raft集群呢，因为集群的启动要配置集群的多个ip，但是容器又没有固定的ip？
你们是怎么解决这个问题的呢？

**Comment by fengjiachun** [comment]
hostname 不是固定的？

**Comment by killme2008** [comment]
这种情况一般是两种处理：

1. 预先分配容器，确定 ip 后部署服务，运维方式采用类似 zk 的方式，通过我们提供的 CliService 做节点的增删管理。
2. 需要和底层容器平台打通，在分配的同时获得 ip 地址，并且在容器上线下线的时候，监听到这些时间，调用 CliService 做节点的自动化增删管理。

**Comment by huangyunbin** [comment]
> hostname 不是固定的？

这边hostname也是不固定的。

**Comment by huangyunbin** [comment]
> 这种情况一般是两种处理：
> 
> 1. 预先分配容器，确定 ip 后部署服务，运维方式采用类似 zk 的方式，通过我们提供的 CliService 做节点的增删管理。
> 2. 需要和底层容器平台打通，在分配的同时获得 ip 地址，并且在容器上线下线的时候，监听到这些时间，调用 CliService 做节点的自动化增删管理。

这两种方式对于我们都不太好做，还有其他更加友好的方式吗？

**Comment by killme2008** [comment]
@huangyunbin 就我所知没有了，本质上你都需要获取你分配到容器 IP 才可以组建起集群，组建后，需要根据节点的上下线做集群管理。
