### ISSUE TITLE
10秒护主中，网络切割恢复后，长时间的脑裂情况怎么处理

### ISSUE THREAD

**Issue by mdyzsz91** [alipay/sofa-jraft#62]
网络切割恢复后，10秒护主模式，有两个leader的情况下如何处理，接收读写、下发到follower写等

**Comment by pifuant** [comment]
假的leader发起的entry, 不会被majority接受

**Comment by killme2008** [comment]
你说的这种情况是不会出现的。通过 leader 租约和 preVote 已经最大程度防止了出现两个 leader，除非出现时钟漂移。其次哪怕出现两个 leader，就像 @pifuant 说的，基本的 raft 协议会保证一个请求只能被一个 leader 接受，因为他需要得到 majority 多数派的确认。
