### ISSUE TITLE
Ballot#init(Configuration conf, Configuration oldConf)怎么理解这两个conf

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#63]
如题

**Comment by killme2008** [comment]
分别表示集群变更前（增删节点）的 conf 和变更后的 conf。

**Comment by gumandy** [comment]
@killme2008 为什么需要两个conf

**Comment by killme2008** [comment]
因为在　membership change 阶段你也需要考虑到容灾（比如 conf change 过程中 leader 当机，重启后应当能继续保证 safty 并继续整个过程），更具体的需要结合论文来阅读

https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf

参见第四节的 Cluster membership changes
