### ISSUE TITLE
NodeImpl#executeApplyingTasks方法疑似bug

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#64]
```java
if (!this.ballotBox.appendPendingTask(this.conf.getConf(), conf.isStable() ? null : conf.getOldConf(),
            task.done)) {
            Utils.runClosureInThread(task.done, new Status(RaftError.EINTERNAL, "Fail to append task."));
            return;
}
```
此处的return不应该是continue更合适吗

**Comment by killme2008** [comment]
这里从运行时和代码路径角度是不会出现 append 失败的，因为他只是添加到内存的 list，里面的 `pending <=0 ` 的判断也只是一个额外的断言，如果出现是 bug；
不过从严谨的代码风格角度修改成 continue 更合适。

感谢反馈。

**Comment by gumandy** [comment]
@killme2008 有很多地方都应该断言，或者抛运行时异常，而不是打日志，阅读起来很容易产生歧义，比如BallotBox#resetPendingIndex(long newPendingIndex)

**Comment by killme2008** [comment]
@gumandy  日志是为了方便调试，特别是生产环境下。断言的话仅在单元测试会运行。

**Comment by gumandy** [comment]
@killme2008 能跑到error日志已经是意料之外的事了（说明程序已经是存在bug了），仅仅打日志也是非常难定位问题，何不把栈也打出来

**Comment by killme2008** [comment]
@gumandy 栈打出来没有意义的，基本也帮助不了分析问题，此外还容易因为太多日志淹没了重要的信息，通过日志前缀，加上日志里的信息，已经足够定位问题，你可以看到我们的日志基本将想要的信息都打印了的。

**Comment by gumandy** [comment]
@killme2008 见仁见智，我还是比较倾向抛运行时异常，起码在出bug时不会偏离运行轨迹

**Comment by fengjiachun** [comment]
已经 fix 并合并到 develop 分支，没其他问题就先关闭了
