### ISSUE TITLE
LogManagerImpl#getEntryFromMemory(long index) 遍历logsInMemory太耗费cpu了

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#65]
Requires.requireTrue(。。。descLogsInMemory()），descLogsInMemory这个操作每次都跑一下也挺happy的

**Comment by killme2008** [comment]
Good catch ! 这里确实是一个优化的点，包括是不是将 logsInMemory 改成无锁的数据结构。

**Comment by fengjiachun** [comment]
主要是这里不应该使用 Requires.requireTrue(), 避免无意义的 descLogsInMemory() 即可

**Comment by killme2008** [comment]
@fengjiachun 不只的，这里我也想过是不是用复合数据结构，再引入一个 concurrent map，这样从 log index -> log entry 的查找速度可以加速。

**Comment by killme2008** [comment]
也可以考虑是不是用 ConcurrentSkipListMap 来替换，同时支持有序和随机查找的需求，并且可以无锁化。

**Comment by gumandy** [comment]
现有这个数据结构，随机删只要移动数组的

**Comment by killme2008** [comment]
@fengjiachun 我记错了，这里是数组定位查找，并没有随机查找的开销，修改这个 `descLogsInMemory` 即可。

**Comment by fengjiachun** [comment]
> 现有这个数据结构，随机删只要移动数组的

确实这个也应该优化一下

**Comment by fengjiachun** [comment]
@killme2008 @gumandy 考虑到数组结构对 cpu cache 更友好, 这里还是沿用数组结构，truncatePrefix 时用 subList(0, indexToRemove).clear() 来优化一下，避免不断的移动数组

**Comment by fengjiachun** [comment]
没有其他问题先关闭了
