### ISSUE TITLE
jraft构建失败

### ISSUE THREAD

**Issue by jewin** [alipay/sofa-jraft#69]
操作系统：mac os
JDK：oracle jdk8
开发工具：idea 2018

jmh基准测试框架的scope为test，项目构建失败；
改为provide后，运行用例失败。
![image](https://user-images.githubusercontent.com/5440811/54988449-6d3df380-4ff1-11e9-8c6a-72e63ce51b1e.png)

**Comment by fengjiachun** [comment]
你好，需要先 mvn clean

**Comment by jewin** [comment]
每次编译构建的命令都是mvn clean compile package

**Comment by fengjiachun** [comment]
@jewin 我的意思是当你用 idea 运行 jraft 中的程序时，先 mvn clean， 不是 mvn clean package

**Comment by fengjiachun** [comment]
@jewin 根本原因是 jmh 和 unit-test 不能同目录，有冲突，近期我们会想办法解决下这个问题，暂时你先可以通过 mvn clean 解决

**Comment by jewin** [comment]
收到

**Comment by yangl** [comment]
升级一下maven-compiler-plugin版本 3.8.0 就OK了！

**Comment by fengjiachun** [comment]
> 升级一下maven-compiler-plugin版本 3.8.0 就OK了！

赞，测试了，确实升级 maven-compiler-plugin 版本就 OK 了
