### ISSUE TITLE
bolt里面的日志怎么没打出来

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#75]
bolt里面的日志怎么没打出来

**Comment by fengjiachun** [comment]
bolt 日志在 bolt 自己的目录里，默认情况下应该是${user.home}/bolt/xxx.log
具体配置见： https://github.com/alipay/sofa-bolt/blob/master/src/main/resources/com/alipay/remoting/log/log4j2/log-conf.xml

**Comment by fengjiachun** [comment]
cc @dbl-x
