### ISSUE TITLE
同一个RpcClient异步调用顺序和最后状态机执行的顺序不同

### ISSUE THREAD

**Issue by marsbible** [alipay/sofa-jraft#76]
现在我希望在一个client上提交大量的请求，这些请求是有前后关系的，不能乱序，如果我使用同一个客户端循环调用invokeWithCallback，那么jraft应该无法保证状态机执行的顺序和invoke的顺序一致吧？那么我只能一个一个的同步调用，速度就会非常慢。
请问这种问题有什么解决方案吗？

**Comment by fengjiachun** [comment]
你好，建议先验证下同步调用是否真的不满足你的性能要求，如果不满足，可以分两步优化
1. client 端做 batch invoke
2. 如果还不满足性能要求可以实现batch+pipeline，不过pipeline实现起来要稍复杂一点

**Comment by marsbible** [comment]
> 你好，建议先验证下同步调用是否真的不满足你的性能要求，如果不满足，可以分两步优化
> 
> 1. client 端做 batch invoke
> 2. 如果还不满足性能要求可以实现batch+pipeline，不过pipeline实现起来要稍复杂一点

嗯，我也在考虑在client做batch invoke，准备测试一下。

**Comment by pifuant** [comment]
zxid like zookeeper？
