### ISSUE TITLE
LogStorage 基于 SPI 可扩展

### ISSUE THREAD

**Issue by fengjiachun** [alipay/sofa-jraft#77]
### Your scenes

方便用户自定义实现 LogStorage，当然，可能不仅仅 LogStorage 需要基于 SPI 扩展

### Your advice

实现一套 SPI 加载机制，可能需要对 ServiceLoader 稍微扩展一下

**Comment by zongtanghu** [comment]
Hi，I look up into the sofa-jraft project initially,can I join you in dingding talk? @fengjiachun

**Comment by fengjiachun** [comment]
@zongtanghu Hi, you can find me in this dingding group: 23127468

**Comment by zongtanghu** [comment]
> @zongtanghu Hi, you can find me in this dingding group: 23127468

Hi I have requested to join in this dingding group.
