### ISSUE TITLE
1.2.5 发布

### ISSUE THREAD

**Issue by fengjiachun** [alipay/sofa-jraft#81]
* [x] 单元测试通过
* [x] jepsen 验证通过
* [ ] 文档补充
* [ ] 发布和 release note

**Comment by fengjiachun** [comment]
---
## 1.2.5
2019-04-01
* Bug Fixex
    - 修复 jmh 与 unit test 代码冲突问题 #69 
    - 修复 snapshot 过大引起的安装失败 bug，会影响新增节点的加入 #79 

* Features
    - LogManagerImpl 中耗费 cpu 部分的代码优化
    - 修正一些单词拼写错误
* Breaking Changes
	- 无

__此版本强烈推荐升级__

**Comment by killme2008** [comment]
@fengjiachun   jepsen 测试已通过。
