### ISSUE TITLE
点Star列表前30里，为何接近一半为两天内注册的全新账号？

### ISSUE THREAD

**Issue by lni** [alipay/sofa-jraft#84]
https://zhuanlan.zhihu.com/p/61034386

下面提到的情况的详细截图在上述知乎文章里都已提供。希望从事实出发，合理讨论，是非曲直自有公论。

上周末与两周前的周末，均发生大量一两天内注册的无头像、无github实际使用用户密集点赞的情况。比如今天下午北京时间4点18分的时候，最近30个点赞者中，有13个是今天和昨天两天注册的全新账号。

这些新号，都是固定点赞几个完全类别、语言都不同的项目，比如jraft和一个与互联网完全无关的IT管理软件。更甚者，有多个账号在两三个小时内注册，并完成对完全一样的四个项目含jraft的点赞。

这样大量的新号的密集点赞的结果就是点赞数不合理增长并将项目推入当天trending榜。

请问，支付宝是受到灰黑产业的“打击报复性点赞攻击”了吗？为何似乎支付宝是这种“打击报复性点赞攻击”的受益方呢？

**Comment by killme2008** [comment]
Star 表示大家对 SOFAJRaft 有兴趣，感谢每一位关注 SOFAJRaft 的开发者。同时，坚决反对刷 Star 的行为也坚决不会做此行为。我们愿意与大家共同维护这里的纯净，并且希望能继续 make something people want。

**Comment by lni** [comment]
没有任何具体行动，不向github报告这些僵尸号，自己也不block这些僵尸，僵尸号的点赞照单全收，就是这样“坚决反对”的？

引用我邮件中那句话，技术开发人员，还是简单诚实一些比较好。
