### ISSUE TITLE
提问：为什么StateMachine的onApply方法需要去调用 closure.run

### ISSUE THREAD

**Issue by xingtanzjr** [alipay/sofa-jraft#87]
问题已解，请关闭或删除该issue

**Comment by fengjiachun** [comment]
你好，感谢关注

> 这段代码看起来像是只要Leader执行成功了，就会向Client发送“执行成功”的response。

StateMachine#onApply() 是在 raft log 被复制到多数派以后才会调用
所以向客户端发送 “执行成功” 的 response 是在 __日志已形成多数派并且在 leader 上执行执行成功__ 这个时间节点

> 但实际情况不应该是Task在RaftGroup中成功后(不仅仅是在leader执行成功)才去向client返回response；

这个不太准确，见上面回复

> 而且这个回调理论上不应该是RAFT框架来调用的吗？为什么需要用户在这个地方来调用？

CounterStateMachine 是业务的状态机，在 jraft 中需要你自己来处理 client 响应

**Comment by pifuant** [comment]
一个entry log会被提交给状态机的前提是已经被group接受了， 所以只需要leader sm apply即可。

**Comment by xingtanzjr** [comment]
谢谢解答

**Comment by killme2008** [comment]
补充下，还有个一个额外的接口 `TaskClosure`，可以用于在日志提交到组内多数派之后，应用到状态机之前回调

```
public interface TaskClosure extends Closure {

    /**
     * Called when task is committed to majority peers of the RAFT group but before it is applied to state machine.
     * 
     * <strong>Note: user implementation should not block this method and throw any exceptions.</strong>
     */
    void onCommitted();
}
```
