### ISSUE TITLE
Multi-Raft初始化时leader的均衡性问题

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#90]
用JRaft实现multi-raft，在初始化时，目前没有办法指定哪个node优先成为leader，这或许会因为节点的启动顺序等因素，造成leader过于集中于某一个节点。有这个可能性吗？能否做下改进？

**Comment by fengjiachun** [comment]
rheakv 模块的话， multi-raft 需要一个 placement driver 角色，在运行时自动平衡 leader 分布，对应逻辑在 rheakv-pd 模块

**Comment by fengjiachun** [comment]
这是 [PD 模块相关文档]( https://github.com/alipay/sofa-jraft/wiki/JRaft-RheaKV-%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97#pd-%E6%A8%A1%E5%9D%97%E5%86%85%E9%83%A8%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B)

**Comment by shiftyman** [comment]
自动均衡可以，但是做leader transfer还是有一定的代价的，比如需要锁定raft group一段时间，对系统会有一定的影响。

我想，multi-raft其实用的挺普遍的，jraft-core其实可以做下支持。比如，在初始化时，可以增加一个api，使某node优先发起选举。这样，用户可以在系统初始化时有倾向性地均衡多个raft group leader。

你认为呢？

**Comment by fengjiachun** [comment]
在我们的设计里，rheakv node 默认每间隔 60 秒就会发送一次心跳包（包含 region 节点的各种状态数据），可以把这个间隔时间调整的更小，比如调整到 10 秒让集群启动后很短时间内就达到 leader 平衡

你说的方案我想了一下貌似比较复杂，集群启动顺序不固定，即使设置某个节点针对某个 group 优先选举也不一定能成功，甚至可能在系统运行一段时间后这个 group 根本就不存在于这个节点上（不一定每个节点包含所有 raft group 副本）

本质上，我觉得 rebalance 还是需要在一个第三方中心节点做，可以在集群启动成功后利用运维控制台手工 rebalance（利用 CliService）；也可以代码自动控制（比如 pd server）；也可以写一段简单代码只做初始化的 leader 平衡（ 比如 benchmark 代码中的[这一段](https://github.com/alipay/sofa-jraft/blob/master/jraft-example/src/main/java/com/alipay/sofa/jraft/benchmark/client/BenchmarkClient.java#L163) ）

**Comment by killme2008** [comment]
@fengjiachun  这个 manual rebalance 应该做成一个 api，用于第一次 setup 集群的时候调用，用户也可以人工触发，自己做 reblanace。

**Comment by fengjiachun** [comment]
@killme2008 恩，其实把这段代码做成 api 也可以，不过这个 api 是需要在集群外的一个中心节点发起调用的

**Comment by fengjiachun** [comment]
先暂定增加一个 manual rebalance api，将在 v1.2.6 中完成这个 feature

**Comment by shiftyman** [comment]
嗯嗯，我也没想到更好的方案，还是外部控制比较好。
