### ISSUE TITLE
获取存活follower

### ISSUE THREAD

**Issue by dehuiliu** [alipay/sofa-jraft#91]
作为leader，想获取存活的follower，通知存活的follower处理数据。

目前存在 com.alipay.sofa.jraft.core.ReplicatorGroupImpl#failureReplicators，但是接口没有提供获取的方法。

**Comment by fengjiachun** [comment]
你好，我们会考虑一下在 cliService 增加一个 getActivePeers api

**Comment by fengjiachun** [comment]
getAlivePeers 可能更好些？

**Comment by dehuiliu** [comment]
为什么在 CliService  中添加 getAlivePeers？

**Comment by fengjiachun** [comment]
> 为什么在 CliService 中添加 getAlivePeers？

leader 以外节点甚至 jraft 集群以外都应可以获取到这存活列表

**Comment by killme2008** [comment]
`Node` 接口添加，同时在 cliService 提供。

**Comment by dehuiliu** [comment]
赞同 killme2008  的提议。

**Comment by fengjiachun** [comment]
抱歉是我没说明白
