### ISSUE TITLE
配置变更中如果移除了当前节点，不会shutdown这个node？

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#94]
如题，从代码看，被移除的node一直还在，不断重复选举超时。

是否应该shutdown这个node？或者是否应该暴露一个接口，当被移除时触发，让业务可以定义这个行为？

**Comment by killme2008** [comment]
1. 移除的节点不再参与服务，从运维角度可以去选择关闭了，就跟机器下线一个道理。
2. 移除跟关闭的 API 设计是正交的，发起移除的操作方，可以在移除确认成功后，继续发起 shutdown 调用。这里并不需要一个 callback 之类的东西，因为移除肯定是主动发起的，用户是知道这个行为的。

**Comment by shiftyman** [comment]
这里我觉得或许可以改进下：移除可以把shutdown带上，addPeer可以把node的bootstrap带上。
因为其实app进程的启动和关闭，跟node的启动和关闭一般是独立的。只要app把rpcServer启动了，就可以把流程聚合在一起了。

另外，shutdown是否也考虑把statemachine的data部分清理下，因为启动时data都会被snapshot覆盖了~

**Comment by killme2008** [comment]
api  设计一定是正交的，你可以自己组合来调用，我们不会去做这个事情。
