### ISSUE TITLE
关于AddPeer的疑问

### ISSUE THREAD

**Issue by shiftyman** [alipay/sofa-jraft#95]
addPeer流程，假设新的node没有任何数据，那么，先把新peer的node启动起来，注意node的initialServerList不能只有这个新peer，可以加上现有的集群列表。
因为如果只有这个新peer，它就会选举自己成为leader。~~
如果initialServerList包括现有的集群列表，那么在对现有集群发送addPeer请求前，这个新peer可能会选举超时，然后发起“预投票”，原有集群的节点会拒绝此次预投票，因为它的term比较小。新peer会stepdown，然后等待下一次选举超时，继续发“预投票”，如此往复。这个过程中，如果对原集群leader进行addPeer，就可以把这个节点加进去。

不知道我的理解对不对？麻烦指教~

**Comment by killme2008** [comment]
你的理解是正确的，一般是推荐第二种方案，让新节点包括原有 server list，然后去 addPeer。

不过 jraft 提供了另外一种启动方式 `NodeImpl#bootstrap(BootstrapOptions)`，主动配置一个新节点，假设你有 snapshot 机制，你还可以主动拷贝 snapshot 到新节点上，然后设置 `BootstrapOptions` 的 `setLastLogIndex` 来配置 snapshot 的 log index 启动，这样启动的节点就可以通过 addPeer 添加到现有集群，由于 snapshot 存在，可以加快节点 catchup。

**Comment by killme2008** [comment]
`bootstrap` 启动的节点不会发起选举，就是一个“空”的新节点，等待被加入到集群。

**Comment by shiftyman** [comment]
“然后设置 BootstrapOptions 的 setLastLogIndex 来配置 snapshot 的 log index 启动“

这个可以详细说明一下吗?setLastLogIndex的作用是？我理解直接根据本地snapshot目录下的数据恢复不就好了吗？

**Comment by killme2008** [comment]
因为 Node 是不知道你这个 snapshot 当时的 log index 是多少，这个只有用户才知道。 snapshot 的元信息不一定有设置，跟你的实现有关系，所以是让你主动设置。

**Comment by killme2008** [comment]
新节点会从 snapshot 的 log index 开始追日志，这也是 snapshot 的作用。如果没有设置 snapshot，那就从 0 开始追，也就不用设置 `setLastLogIndex`。

**Comment by shiftyman** [comment]
snapshot之后在onSnapshotSaveDone方法不是会将snapshot的meta信息写入文件吗？其中就包括了snapshot时的log index不是吗？为什么还需要设置？
用户也不知道这个index吧，snapshot在后台定时跑的，用户怎么知道？

**Comment by killme2008** [comment]
1.  snapshot 都有日志告诉你 log index，并且 snapshot 的 metadata 的文件名就是 logindex
2. 目前设置 last log index 更多还是为了在启动的阶段校验。

**Comment by shiftyman** [comment]
ok，thks
