### ISSUE TITLE
没有处理 RaftMetaStorage 的异常返回

### ISSUE THREAD

**Issue by ylgrgyq** [alipay/sofa-jraft#96]
感谢开发者的辛苦工作。

### Describe the bug

Raft 的 meta 信息对 Raft 正常工作来说至关重要，看上去目前 [LocalRaftMetaStorage](https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LocalRaftMetaStorage.java#L113) 存储 Meta 信息时虽然会捕获 IO 异常，但仅仅是打日志和返回 false 表示存 meta 失败，使用 RaftMetaStorage 的地方均未检查返回值是否是 false，(比如 [这里](https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L882) [这里](https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L988) [这里](https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1444)) 也即相当于当出现 IO 异常时候仅仅只有日志记录，此后 Raft 一旦重启，恢复的 Meta 信息就是错的。

比如可能出现在某个 Term 100 下已经 Vote 过某个节点 A 为 Leader，结果 Meta 没存成功又异常重启了，启动后就忘记自己在 Term 100 下 Vote 过 A 节点为 Leader (可能恢复的是老 Term 下的 Vote For)，于是在 term 100 下又能 Vote 另一个节点为 Leader 了，从而违反了 Raft 的约定。

不知道是不是我遗漏了什么信息，如有理解错误还望见谅。

### Expected behavior

处理 RaftMetaStorage 存 meta 失败时返回的 false 值，存失败时候是不是可以考虑将整个节点停止。

### Actual behavior

看上去没有任何地方处理 RaftMetaStorage 在存 Meta 失败后返回的 false 值。

### Steps to reproduce

比如在 Raft 启动后，将存储 Meta 的路径完全删除或修改权限让 Raft 进程无权操作目标路径。

但看上去这里真的想引起问题可能不太容易，比如即使存 Meta 失败，当前进程只要不重启就还能保持正确，即使重启只要 Leader 还在没发生选举能收到 Leader 的数据就还能在重启后更新 term 到正确值，不过看上去是有隐患在。

### Environment

- SOFAJRaft version: v1.2.5
- JVM version (e.g. `java -version`): 任意
- OS version (e.g. `uname -a`): 任意
- Maven version: 任意
- IDE version: 任意

**Comment by killme2008** [comment]
是的，这里确实没有去检测返回值，不过这个并不会影响 raft 协议的正确性，只是可能出现不必要的选举和日志截断和复制。

不过这里可能抛出异常，然后调用到 `FSMCaller#onError` 更合适，这样可以使得整个状态机处于错误状态而暂停。

**Comment by ylgrgyq** [comment]
> 是的，这里确实没有去检测返回值，不过这个并不会影响 raft 协议的正确性，只是可能出现不必要的选举和日志截断和复制。

哦 是说即使出现忘掉 vote for 短暂选出来两个 Leader， Log 在 Replicate 到 Follower 时候因为老 Leader 实际没有足够 Follower 所以无法 commit 任何 Log 所以至少一致性的保证上没事奥。这个同意。我是基于论文里说同一个 term 下保证只 vote 一次担心这个保证不在的话什么地方会出问题。

还看到[发现 split brain 时候有个重选举的处理](https://github.com/alipay/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1564)感觉挺好的。

> 不过这里可能抛出异常，然后调用到 `FSMCaller#onError` 更合适，这样可以使得整个状态机处于错误状态而暂停。

👏 👏 👏

**Comment by killme2008** [comment]
@ylgrgyq  从实际情况看，应该不会出现一个 term 投票两次。

1. 在 save raft meta 失败后，但是产生了 leader，这时候该错误节点重启，他会直接被转化为 follower 。
2. 在 save raft meta 失败后，没有产生 leader，发起投票的 Candidate 会递增 term ，重新发起投票，错误节点重启，他收到的投票 term 已经递增改变，没有违反一个 term 投票一次的承诺。

不过我同意这里的处理确实有隐患，还是 halt 整个状态机安全。
