### ISSUE TITLE
wiki 使用git clone到本地后,没有"扩展资料">"分布式一致性: Raft 与 JRaft"相关内容，请问如何得到完整的wiki文档？

### ISSUE THREAD

**Issue by techzealot** [alipay/sofa-jraft#97]
### Your question

wiki 使用git clone到本地后,没有"扩展资料">"分布式一致性: Raft 与 JRaft"相关内容，请问如何得到完整的wiki文档？

### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
git clone https://github.com/alipay/sofa-jraft.wiki
我试了下是完整文档啊

**Comment by techzealot** [comment]
> git clone https://github.com/alipay/sofa-jraft.wiki
> 我试了下是完整文档啊
![image](https://user-images.githubusercontent.com/19412179/56116309-1300d480-5f98-11e9-88f8-792b13180f6c.png)
您好，大部分都可以找到，只有”分布式一致性: Raft 与 JRaft”这部分内容没有找到

**Comment by fengjiachun** [comment]
难道又是 windows 的问题？ 我们没有 windows 环境，猜测可能是 windows 不能创建包含 ':' 的文件，我改下名字你再试试

**Comment by fengjiachun** [comment]
@techzealot 我改了文件名字，麻烦你再试试，抱歉给你带来不便

**Comment by techzealot** [comment]
> @techzealot 我改了文件名字，麻烦你再试试，抱歉给你带来不便

谢谢，我又试了下，这次可以了
